name: Build (Windows, MSBuild)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
        platform: [x64]   # change to [x64, x86] if you want both

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        run: msbuild .\FastDriveScan.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /m

      - name: Collect artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: FastDriveScanner-${{ matrix.platform }}-${{ matrix.configuration }}
          path: |
            **\${{ matrix.platform }}\${{ matrix.configuration }}\*.exe
            **\${{ matrix.configuration }}\*.exe
          if-no-files-found: warn
